"""Pre-registration protocol: hash-chained registration, amendments, sealed results, verdicts."""

from adversary.protocol.planted import (
    Plant,
    PlantManifest,
    RecallReport,
    RelativeRecall,
    leaked_canaries,
    recall,
    relative_recall,
)
from adversary.protocol.preregistration import (
    Amendment,
    Condition,
    KillRule,
    Preregistration,
    PreregistrationError,
    RegionHash,
    Registration,
    amend,
    current_entries,
    current_preregistration_sha256,
    extract_region,
    load_amendments,
    load_registration,
    parse_sidecar,
    register,
    seal_results,
    verify,
    verify_sidecar,
)
from adversary.protocol.verdict import (
    ConditionResult,
    ExperimentVerdict,
    RuleResult,
    decide,
    evaluate,
    outcome_of,
)

__all__ = [
    "Amendment",
    "Condition",
    "ConditionResult",
    "ExperimentVerdict",
    "KillRule",
    "Preregistration",
    "Plant",
    "PlantManifest",
    "RelativeRecall",
    "PreregistrationError",
    "RecallReport",
    "RegionHash",
    "Registration",
    "RuleResult",
    "amend",
    "current_entries",
    "current_preregistration_sha256",
    "decide",
    "evaluate",
    "extract_region",
    "load_amendments",
    "leaked_canaries",
    "load_registration",
    "outcome_of",
    "parse_sidecar",
    "recall",
    "register",
    "relative_recall",
    "seal_results",
    "verify",
    "verify_sidecar",
]
