"""Statistics over episodes. Pure functions; nothing here touches a model."""

from adversary.stats.association import RankAssociation, spearman
from adversary.stats.calibration import (
    CentralEstimate,
    Detectability,
    EquivalenceBelow,
    ReferenceMagnitude,
    central_estimate,
    detectability,
    equivalent_below,
    forced_rate_for_excess,
    reference_magnitude,
)
from adversary.stats.cost import (
    BudgetLedger,
    Prices,
    Spend,
    YieldCurve,
    compute_hours,
    ledger_of,
    per_compute_hour,
    yield_curve,
)
from adversary.stats.equivalence import (
    BootstrapResult,
    EquivalenceResult,
    McNemarResult,
    mcnemar_test,
    paired_bootstrap,
    tost_paired,
)
from adversary.stats.excess import (
    Baseline,
    ExcessEstimate,
    estimate_excess,
    excess_over_additive,
    hot_cells,
    main_effects_fit,
)
from adversary.stats.honesty import HonestyReport, HonestyShift, honesty_report, honesty_shift
from adversary.stats.importance import Importance, PrevalenceEstimate, rank
from adversary.stats.interaction_order import InteractionOrderCurve, interaction_order_curve
from adversary.stats.mobius import BranchAgreement, MobiusSynergy, branch_agreement, mobius_synergy
from adversary.stats.multiplicity import (
    AlphaSpending,
    EProcess,
    PermutationNull,
    benjamini_hochberg,
    permutation_null,
)
from adversary.stats.rates import (
    Comparison,
    RateEstimate,
    compare_arms,
    compare_rates,
    failure_rate,
    in_cell,
    measurable,
    rate_estimate,
    wilson_interval,
    zero_failure_bound,
)
from adversary.stats.regions import (
    CellCounts,
    Region,
    RegionTest,
    cluster_regions,
    homogeneity,
    lrt_common_excess,
    one_region,
)
from adversary.stats.species import (
    SpeciesEstimate,
    ValidityCheck,
    species_estimate,
    validity_check,
)

__all__ = [
    "AlphaSpending",
    "Baseline",
    "BootstrapResult",
    "BranchAgreement",
    "BudgetLedger",
    "CellCounts",
    "CentralEstimate",
    "Comparison",
    "Detectability",
    "EProcess",
    "EquivalenceBelow",
    "EquivalenceResult",
    "ExcessEstimate",
    "HonestyReport",
    "HonestyShift",
    "Importance",
    "InteractionOrderCurve",
    "McNemarResult",
    "MobiusSynergy",
    "PermutationNull",
    "PrevalenceEstimate",
    "Prices",
    "RankAssociation",
    "RateEstimate",
    "ReferenceMagnitude",
    "Region",
    "RegionTest",
    "SpeciesEstimate",
    "Spend",
    "ValidityCheck",
    "YieldCurve",
    "benjamini_hochberg",
    "branch_agreement",
    "central_estimate",
    "cluster_regions",
    "compare_arms",
    "compare_rates",
    "compute_hours",
    "detectability",
    "equivalent_below",
    "estimate_excess",
    "excess_over_additive",
    "failure_rate",
    "forced_rate_for_excess",
    "homogeneity",
    "honesty_report",
    "honesty_shift",
    "hot_cells",
    "in_cell",
    "interaction_order_curve",
    "ledger_of",
    "lrt_common_excess",
    "main_effects_fit",
    "mcnemar_test",
    "measurable",
    "mobius_synergy",
    "one_region",
    "paired_bootstrap",
    "per_compute_hour",
    "permutation_null",
    "rank",
    "rate_estimate",
    "reference_magnitude",
    "spearman",
    "species_estimate",
    "tost_paired",
    "validity_check",
    "wilson_interval",
    "yield_curve",
    "zero_failure_bound",
]
